"""pruebaalembic

Revision ID: 6a37fa5cadbd
Revises: 0001_baseline
Create Date: 2026-10-06 06:04:55.847302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a37fa5cadbd'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('certificate_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='in_progress', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('issued_at_override', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validity_extension', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('issued_certificate_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'issued')", name=op.f('ck_pending_certificates_status')),
    sa.ForeignKeyConstraint(['certificate_type_id'], ['certificate_types.id'], name=op.f('fk_pending_certificates_certificate_type_id_certificate_types')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_pending_certificates_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_pending_certificates_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_certificate_id'], ['certificates.id'], name=op.f('fk_pending_certificates_issued_certificate_id_certificates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pending_certificates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_certificates')),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_pending_user_course')
    )
    op.alter_column('certificates', 'hours',
               existing_type=sa.INTEGER(),
               comment='Override de intensidad horaria (NULL = sigue el tipo)',
               existing_nullable=True)
    op.alter_column('certificates', 'validity_years',
               existing_type=sa.INTEGER(),
               comment='Override de vigencia en años (NULL = sigue el tipo)',
               existing_nullable=True)
    op.drop_column('courses', 'image_url')
    op.drop_column('courses', 'preset_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('preset_image', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.alter_column('certificates', 'validity_years',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Override de vigencia en años (NULL = sigue el tipo)',
               existing_nullable=True)
    op.alter_column('certificates', 'hours',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Override de intensidad horaria (NULL = sigue el tipo)',
               existing_nullable=True)
    op.drop_table('pending_certificates')
    # ### end Alembic commands ###