"""add column comments

Revision ID: bd64fa7d19c2
Revises: 0001_baseline
Create Date: 2026-10-06 19:21:53.181002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd64fa7d19c2'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificates', 'hours',
               existing_type=sa.INTEGER(),
               comment='Override de intensidad horaria (NULL = sigue el tipo)',
               existing_nullable=True)
    op.alter_column('certificates', 'validity_years',
               existing_type=sa.INTEGER(),
               comment='Override de vigencia en años (NULL = sigue el tipo)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificates', 'validity_years',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Override de vigencia en años (NULL = sigue el tipo)',
               existing_nullable=True)
    op.alter_column('certificates', 'hours',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Override de intensidad horaria (NULL = sigue el tipo)',
               existing_nullable=True)
    # ### end Alembic commands ###